# Generated by Django 3.2.5 on 2021-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('transporte', models.CharField(choices=[('Transporte_Compartido', 'Transporte_Compartido'), ('Alquiler_de_Vehiculos', 'Alquiler_de_Vehiculos')], max_length=50)),
                ('hotel', models.CharField(choices=[('Hotel', 'Hotel'), ('Airbnb', 'AirBnB')], max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
