# Generated by Django 3.2.5 on 2021-07-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('transporte', models.CharField(choices=[('Transporte_Compartido', 'Transporte_Compartido'), ('Alquiler_de_Vehiculos', 'Alquiler_de_Vehiculos')], max_length=50)),
                ('hotel', models.CharField(choices=[('Hotel', 'Hotel'), ('Airbnb', 'AirBnB')], max_length=50)),
                ('tour', models.CharField(choices=[('Tour_a_Punta Cana', 'Tour_a_Punta Cana'), ('Tour_a_Macchu Picchu', 'Tour_a_Macchu Picchu'), ('Tour_a_Paris', 'Tour_a_Paris'), ('Tour_a_Londres', 'Tour_a_Londres'), ('Tour_a_Cancun', 'Tour_a_Cancun'), ('Tour_a_Isla de Pascua', 'Tour_a_Isla de Pascua')], max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
