# Generated by Django 3.2.5 on 2021-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_auto_20210707_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fecha',
            field=models.CharField(max_length=15),
        ),
    ]
